insert into to_do(id, username, description, target_date, status)
values(10001, 'mishael', 'Learn to be awesome', sysdate(), false);
insert into to_do(id, username, description, target_date, status)
values(10002, 'Rahul', 'Travel to India', sysdate(), false);
insert into to_do(id, username, description, target_date, status)
values(10003, 'mishael', 'Shift to Bangalore', sysdate(), false);
insert into to_do(id, username, description, target_date, status)
values(10004, 'mark', 'Shift to Cochin', sysdate(), false);
insert into to_do(id, username, description, target_date, status)
values(10005, 'mark', 'Swim to England', sysdate(), false);